config/routes.rb
Ears2::Application.routes.draw do
  get "lessons/show"
  get "stats/show"
  match '/about' => 'home#about', :via => [:get]
  match '/pricing' => 'home#pricing', :via => [:get]
  get "home/pricing"


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  resources :lessons, :only => [:show, :index]
  resources :lessons do
    resources :quizzes, :only => [:index, :show, :new, :create]
  end


end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def new
  	@user_id = current_user.id
    @lesson_id = params[:lesson_id]
  	@lesson = Lesson.find(params[:lesson_id])
    questions = Question.where(:lesson_id => params[:lesson_id])
    @question_answers = Hash.new
    questions.each do |question|
      @question_answers["#{question.answer}"] = "#{question.answer}"
    end
    @question1 = Question.where(:lesson_id => params[:lesson_id]).shuffle[1]
    @question2 = Question.where(:lesson_id => params[:lesson_id]).shuffle[1]
    @question3 = Question.where(:lesson_id => params[:lesson_id]).shuffle[1]
    @question4 = Question.where(:lesson_id => params[:lesson_id]).shuffle[1]
    @question5 = Question.where(:lesson_id => params[:lesson_id]).shuffle[1]
    @question1_answer = @question1.answer
  
  end

  def create
    @question1_score = params[:user_answer1] == params[:correct_answer1] ? 1 : 0
    @question2_score = params[:user_answer2] == params[:correct_answer2] ? 1 : 0
    @question3_score = params[:user_answer3] == params[:correct_answer3] ? 1 : 0
    @question4_score = params[:user_answer4] == params[:correct_answer4] ? 1 : 0
    @question5_score = params[:user_answer5] == params[:correct_answer5] ? 1 : 0
    @score = @question1_score + @question2_score + @question3_score + @question4_score + @question5_score
    @lesson_id = params[:lesson_id]
    
    @quiz = Quiz.create!(:score => @score, :lesson_id => params[:lesson_id], :user_id => params[:user_id])
    Response.create!(:question_id => params[:question_id_1],:user_answer => params[:user_answer1], :correct_answer => params[:correct_answer1], :lesson_id => params[:lesson_id], :octave => params[:octave1], :user_id => params[:user_id])
    current_user.question_rating(params[:user_answer1], params[:octave1], params[:question_id_1])
    Response.create!(:question_id => params[:question_id_2],:user_answer => params[:user_answer2], :correct_answer => params[:correct_answer2], :lesson_id => params[:lesson_id], :octave => params[:octave2], :user_id => params[:user_id])
    current_user.question_rating(params[:user_answer2], params[:octave2], params[:question_id_2])
    Response.create!(:question_id => params[:question_id_3],:user_answer => params[:user_answer3], :correct_answer => params[:correct_answer3], :lesson_id => params[:lesson_id], :octave => params[:octave3], :user_id => params[:user_id])
    current_user.question_rating(params[:user_answer3], params[:octave3], params[:question_id_3])
    Response.create!(:question_id => params[:question_id_4],:user_answer => params[:user_answer4], :correct_answer => params[:correct_answer4], :lesson_id => params[:lesson_id], :octave => params[:octave4], :user_id => params[:user_id])
    current_user.question_rating(params[:user_answer4], params[:octave4], params[:question_id_4])
    Response.create!(:question_id => params[:question_id_5],:user_answer => params[:user_answer5], :correct_answer => params[:correct_answer5], :lesson_id => params[:lesson_id], :octave => params[:octave5], :user_id => params[:user_id])
    current_user.question_rating(params[:user_answer5], params[:octave5], params[:question_id_5])
    current_user.lesson_rating(params[:lesson_id])
    @et_recommendations = current_user.et_recommendations
    @cp_recommendations = current_user.cp_recommendations
    
    if @score == 5
      flash[:notice] = "Perfect! You got #{@score} out of 5 on that one!"
    elsif @score == 4
      flash[:notice] = "Excellent! You got #{@score} out of 5 on that one!"
    elsif @score == 3 
      flash[:notice] = "Great work! You got #{@score} out of 5 on that one!"
    elsif @score == 2
      flash[:notice] = "Not bad! You got #{@score} out of 5 one that one!"
    elsif @score == 1
      flash[:notice] = "Hmmm.. you might need some more practice. You got #{@score} out of 5 on that one."
    else
      flash[:notice] = "Keep at it and you'll start to get it! You got #{@score} out of 5 on that one."
    end
    render 'show' 
  end

  def show
  end

  def index
  end

end

app/views/quizzes/new.html.erb
<br>
<br>
<div class="quiz_page_title">
  <h1>Quiz for <%= @lesson.title %></h1>
  <p style="color: #e56b00;">Select Answers and Submit Quiz</p>
</div>
<br>


<div class="row">
<div class="quiz_box span9 offset1">
<%= form_tag(lesson_quizzes_path, :method => "post") do %>

  <div style="height:30px;"></div>

  <div class="question">
    <p>Question 1</p>
    <audio controls>
      <source src="<%= @question1.audioclip_mp3.url %>" preload="auto">
      <source src="<%= @question1.audioclip_wav.url %>" preload="auto">
      Your browser does not support MP3 or WAV files. 
    </audio>
    <%= hidden_field_tag(:correct_answer1, @question1.answer) %>
    <%= hidden_field_tag :question_id_1, @question1.id %>
    <%= hidden_field_tag(:octave1, @question1.octave) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
    <%= hidden_field_tag(:user_id, @lesson.id) %>
   <span class="answer_text">Answer: <%= select_tag(:user_answer1, options_for_select(@question_answers)) %></span>
  </div>
  <hr>

  <div class="question">
    <p>Question 2</p>
    <audio controls>
      <source src="<%= @question2.audioclip_mp3.url %>" preload="auto">
      <source src="<%= @question2.audioclip_wav.url %>" preload="auto">
      Your browser does not support MP3 or WAV files. 
    </audio>
    <%= hidden_field_tag :correct_answer2, @question2.answer %>
    <%= hidden_field_tag :question_id_2, @question2.id %>
    <%= hidden_field_tag(:octave2, @question2.octave) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
    <%= hidden_field_tag(:user_id, @user_id) %>
    <span class="answer_text">Answer: <%= select_tag(:user_answer2, options_for_select(@question_answers)) %></span>
  </div>
  <hr>
  
   <div class="question">
    <p>Question 3</p>
    <audio controls>
      <source src="<%= @question3.audioclip_mp3.url %>" preload="auto">
      <source src="<%= @question3.audioclip_wav.url %>" preload="auto">
      Your browser does not support MP3 or WAV files. 
    </audio>
    <%= hidden_field_tag :correct_answer3, @question3.answer %>
    <%= hidden_field_tag :question_id_3, @question3.id %>
    <%= hidden_field_tag(:octave3, @question3.octave) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
    <%= hidden_field_tag(:user_id, @user_id) %>
    <span class="answer_text">Answer: <%= select_tag(:user_answer3, options_for_select(@question_answers)) %></span>
  </div>
  <hr>

   <div class="question">
    <p>Question 4</p>
    <audio controls>
      <source src="<%= @question4.audioclip_mp3.url %>" preload="auto">
      <source src="<%= @question4.audioclip_wav.url %>" preload="auto">
      Your browser does not support MP3 or WAV files. 
    </audio>
    <%= hidden_field_tag :correct_answer4, @question4.answer %>
    <%= hidden_field_tag :question_id_4, @question4.id %>
    <%= hidden_field_tag(:octave4, @question4.octave) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
    <%= hidden_field_tag(:user_id, @user_id) %>
    <span class="answer_text">Answer: <%= select_tag(:user_answer4, options_for_select(@question_answers)) %></span>
  </div>
  <hr>

  <div class="question question_last">
    <p>Question 5</p>
    <audio controls>
      <source src="<%= @question5.audioclip_mp3.url %>" preload="auto">
      <source src="<%= @question5.audioclip_wav.url %>" preload="auto">
      Your browser does not support MP3 or WAV files. 
    </audio>
    <%= hidden_field_tag :correct_answer5, @question5.answer %>
    <%= hidden_field_tag :question_id_5, @question5.id %>
    <%= hidden_field_tag(:octave5, @question5.octave) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
    <%= hidden_field_tag(:user_id, @user_id) %>
    <span class="answer_text">Answer: <%= select_tag(:user_answer5, options_for_select(@question_answers)) %></span>
  </div>
  
  <br>
  <div width="span3" style="text-align: center;">
    <%= submit_tag("Submit Answers", {:class => "btn btn-primary"}) %>
  </div>
<% end %>
</div>
</div>


<hr>

<p>Congrats in advance! You're on your way to being a better musician.</p>

app/views/quizzes/show.html.erb
<div class="span8 offset2 quiz_results">
  
  <div class="quiz_results_options_header">
  	<h4>Congrats! Every practice session matters... what do you want to do next?</h4>
  </div>
  
  <div class="quiz_results_options_body">
    <ul style="padding-top: 10px; padding-left: 15px;">
      <li><%= link_to 'Check Out Some Ear Training Lessons', lessons_path %></li><br>
        <ul class="recommendations">
        <% @et_recommendations.each do |et_recommendation| %>
          <li><%= link_to et_recommendation[0], lesson_path(:id => et_recommendation[2]) %></li>
        <% end %>
        </ul>
        <br>

      
      <% if current_user.roles.first.name == 'gold' or current_user.roles.first.name == 'platinum' or current_user.roles.first.name == 'admin'  %>
      <li><%= link_to 'Work on Chord Progressions', content_gold_path %></li><br>
        <ul class="recommendations">
        <% @cp_recommendations.each do |cp_recommendation| %>
          <li><%= link_to cp_recommendation[0], lesson_path(:id => cp_recommendation[2]) %></li>
        <% end %>
        </ul>
      <% end %>
      <br>
      <li><%= link_to 'See Your Stats', "../../../stats/show" %></li>
      
    </ul>
    <br>
  </div>

</div>