config/routes.rb
Ears2::Application.routes.draw do
  get "lessons/show"
  get "stats/show"
  match '/about' => 'home#about', :via => [:get]
  match '/pricing' => 'home#pricing', :via => [:get]
  get "home/pricing"


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  resources :lessons, :only => [:show, :index]
  resources :lessons do
    resources :quizzes, :only => [:index, :show, :new, :create]
  end


end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>

<%= link_to image_tag('eartutor_white.png', :class => 'image-logo'), root_path %>

<div class="nav-collapse collapse nav-spacing">
  <ul class="nav pull-right">
 
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Users', users_path %>
      </li>
      <li>
      <%= link_to 'Models', admin_dashboard_path %>
      </li>
    <% end %>
   <li>
    <%= link_to 'Ear Training', lessons_path %>
    </li>
    <% if current_user.roles.first.name == 'gold' or current_user.roles.first.name == 'platinum' or current_user.roles.first.name == 'admin'  %>
      <li><%= link_to 'Chord Progressions', content_gold_path %></li>
    <% end %>
    <li>
    <%= link_to 'Stats', "../../../stats/show" %>
    </li>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
     <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
      <%= link_to 'Home', root_path %> 
    </li>
    <li>
      <%= link_to 'About', about_path %> 
    </li> 
    <li>
      <%= link_to 'Pricing', pricing_path %> 
    </li>
    <li>
      <%= link_to 'Blog', "../blog/" %> 
    </li>    
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
 
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ear Training Software | EarTutor" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ear Training Software | EarTracker" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

    <% if Rails.env == "production" %>
    <!-- starts Google Analytics -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42420336-1', 'eartutor.com');
    ga('send', 'pageview');

    </script>
    <!-- ends Google Analytics -->
    <% end %>

  </head>
  <body class="<%= controller_name %> <%= action_name %> pull-top">
    <div class="navbar navbar-inverse navbar-static-top shadow">
      <div class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
         
        </div>
        <%= debug(params) if Rails.env.development? %>
      </div> <!--! end of .container -->
	 <!-- starts footer -->
	    <footer id="footer">
	        <div class="container">
	            <div class="row info">
	                <div class="span12" style="margin: 0 auto; text-align: center;">
	                    <ul>
	                        <li>Toronto, Canada</li>
	                        <li><a href="mailto:brad@bradmilne.ca">Email Me!</a></li>
	                    </ul>
	                </div>
	         
	                    <div class="row copyright" style="text-align: center;">
	                        <div class="span12">
	                            © 2013 EarTutor
	                        </div>
	                    </div>
	                </div>            
	            </div>
	        </div>
	    </footer>
    </div> <!--! end of #main -->


<% if Rails.env == "production" %>
    <!-- CrazyEgg Tracking -->
    <script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0017/9429.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('9669-208-10-1804');/*]]>*/</script><noscript><a href="https://www.olark.com/site/9669-208-10-1804/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->
 <% end %>
  </body>
</html>